version: '3.8'

services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    networks:
      - my_network
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - my_network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - my_network
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # Test Web Server (e.g., Nginx)
  webserver:
    image: nginx:latest
    container_name: webserver
    networks:
      - my_network
    ports:
      - "8081:80"
    restart: always

    # Optionally, you could add a health check or logging here for more control

  # Test Client (simple Alpine container that makes HTTP requests)
  client:
    image: alpine:latest
    container_name: client
    networks:
      - my_network
    command: /bin/sh -c "apk add --no-cache curl && while true; do curl -s http://webserver; sleep 2; done"
    restart: always

  # Another Test Server (example: simple Python HTTP server)
  pythonserver:
    image: python:3.9-slim
    container_name: pythonserver
    networks:
      - my_network
    command: /bin/bash -c "python3 -m http.server 80"
    restart: always

networks:
  my_network:
    driver: bridge

